# ---ARRAYS---

In [1]:
import numpy


In [2]:
import numpy as np

arr = np.array([1,2,3,4])

print(arr)


[1 2 3 4]


# ---ARRAY SORTING---

In [3]:
arr1 = np.array([[[5,6], [7,8], [1.2],[3,4]]])
print(arr1.ndim)


3


In [4]:
print(np.sort(arr1))

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


# ---ARRAY SEARCHING---

In [7]:
arr2 = np.array([[[12,15],[14,16],[18,20],[21,23]]])
z = np.where(arr2==18)
print (z)
print(arr2.ndim)

(array([0]), array([2]), array([0]))
3
